### ISSUE TITLE
コース詳細ページの作成

### ISSUE THREAD

**Issue by a2h1r0** [a2h1r0/CLOTO#22]
# 単一記事ページを作成

- [x] タイトル
- [x] 投稿者
- [ ] カテゴリ
- [ ] タグ：他のユーザーも追加可(？)
- [x] ネタの内容
- [ ] みんなの活動記録(写真？)
- [ ] 参加ボタン +  ネタへの参加者一覧
1. 参加前：参加する
2. 参加後：辞める & 完成した
- [ ] コメント(返信機能)
- [ ] いいね + 数

**コメントの削除は，記事投稿者もしくはコメント投稿者のみ可能**

**Comment by shutoushu** [comment]
今日からいじり始めます
