### ISSUE TITLE
活動記録フォームの作成

### ISSUE THREAD

**Issue by a2h1r0** [a2h1r0/CLOTO#31]
# Jamp from #22 
**活動記録の投稿フォームの作成**

- [x] ユーザーID
- [x] コースID
- [x] タイトル
- [x] 活動時間
- [x] 進捗画像
- [x] ひとことコメント
- [x] 完成ボタン

完成ボタン押下時にはhiddenでfinish要素を送信し，その値から条件分岐する．

**Comment by shutoushu** [comment]
アイデアルームは　活動記録（写真）が貼られているページ

活動記録ページとは活動記録（写真）をクリックしたときのページ

**Comment by a2h1r0** [comment]
次はフロント側のjs処理の実装．finishのvalue変更など．

あと，フォームにBootstrapValidatorでも当てたほうが良いかも．
現状，Requestエラー時のリロードでトリミング済の画像が消える．

**Comment by a2h1r0** [comment]
BootstrapValidatorの件はUI調整段階で対応する．
